Import the 1.0.140 release

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -10,7 +10,7 @@ export PATH
 
 ###########################################################################
 
-if [ -z "$DEBOOTSTRAP_DIR" ]; then
+if [ -z "${DEBOOTSTRAP_DIR-}" ]; then
 	if [ -x /debootstrap/debootstrap ]; then
 		DEBOOTSTRAP_DIR=/debootstrap
 	else
@@ -113,10 +113,12 @@ usage()
       --no-merged-usr        do not make /{bin,sbin,lib}/ symlinks to /usr/
                              (default for older Debian suites)
       --keyring=K            check Release files against keyring K
-      --no-check-gpg         avoid checking Release file signatures
-      --force-check-gpg      force checking Release file signatures
+      --no-check-sig         avoid checking Release file signatures
+      --no-check-gpg         deprecated alias for --no-check-sig
+      --force-check-sig      force checking Release file signatures
                              (also disables automatic fallback to HTTPS in case
                              of a missing keyring), aborting otherwise
+      --force-check-gpg      deprecated alias for --force-check-sig
       --no-resolve-deps      don't try to resolve dependencies automatically
       --log-extra-deps       record extra dependency info in debootstrap.log
       --cache-dir=DIR        Use specified directory as package cache directory
@@ -160,7 +162,7 @@ if [ $# != 0 ] ; then
 		exit 0
 		;;
 	    --debian-installer)
-		if ! (echo -n "" >&3) 2>/dev/null; then
+		if ! (printf "" >&3) 2>/dev/null; then
 			error 1 ARG_DIBYHAND "If running debootstrap by hand, don't use --debian-installer"
 		fi
 		USE_DEBIANINSTALLER_INTERACTION=yes
@@ -356,7 +358,7 @@ if [ $# != 0 ] ; then
 		;;
 	    --cache-dir|--cache-dir=?*)
 		# Okay, let's check user's option
-		if [ "$1" = "--cache-dir" ] && [ -n "$2" ] ; then
+		if [ "$1" = "--cache-dir" ] && [ -n "${2-}" ] ; then
 			CACHE_DIR="$2"
 			shift 2
 		elif [ "$1" != "${1#--cache-dir=}" ]; then
@@ -365,7 +367,7 @@ if [ $# != 0 ] ; then
 		else
 			error 1 NEEDARG "option requires an argument %s" "$1"
 		fi
-		if [ ! -z "${CACHE_DIR##/*}" ]; then
+		if [ -n "${CACHE_DIR##/*}" ]; then
 			error 1 NOTABSOLUTEPATH "cache directory should be specified with an absolute path"
 		fi
 		if [ ! -d "$CACHE_DIR" ] ; then
@@ -381,8 +383,8 @@ if [ $# != 0 ] ; then
 		shift
 		;;
 	    --keyring|--keyring=?*)
-		if ! gpgv --version >/dev/null 2>&1; then
-			error 1 NEEDGPGV "gpgv not installed, but required for Release verification"
+		if ! in_path sopv && ! in_path sqv && ! in_path gpgv; then
+			error 1 NEEDPGPV "none of sopv, sqv or gpgv are installed, but required for Release verification"
 		fi
 		if [ "$1" = "--keyring" ] && [ -n "$2" ]; then
 			KEYRING="$2"
@@ -397,11 +399,11 @@ if [ $# != 0 ] ; then
 			error 1 KEYRING "specified keyring file ($KEYRING) not found"
 		fi
 		;;
-	    --no-check-gpg)
+	    --no-check-sig|--no-check-gpg)
 			shift 1
 			DISABLE_KEYRING=1
 		;;
-	    --force-check-gpg)
+	    --force-check-sig|--force-check-gpg)
 			shift 1
 			FORCE_KEYRING=1
 		;;
@@ -410,10 +412,10 @@ if [ $# != 0 ] ; then
 			CERTIFICATE="--certificate=$2"
 			shift 2
 		elif [ "$1" != "${1#--certificate=}" ]; then
-			CERTIFICATE="--certificate=${1#--certificate=}" 
+			CERTIFICATE="--certificate=${1#--certificate=}"
 			shift 1
 		else
-		       error 1 NEEDARG "option requires an argument %s" "$1" 
+		       error 1 NEEDARG "option requires an argument %s" "$1"
 		fi
 		;;
 	    --private-key|--private-key=?*)
@@ -421,10 +423,10 @@ if [ $# != 0 ] ; then
 			PRIVATEKEY="--private-key=$2"
 			shift 2
 		elif [ "$1" != "${1#--private-key=}" ]; then
-			PRIVATEKEY="--private-key=${1#--private-key=}" 
+			PRIVATEKEY="--private-key=${1#--private-key=}"
 			shift 1
 		else
-		       error 1 NEEDARG "option requires an argument %s" "$1" 
+		       error 1 NEEDARG "option requires an argument %s" "$1"
 		fi
 		;;
 	    --no-check-certificate)
@@ -471,7 +473,7 @@ fi
 
 ###########################################################################
 if [ -n "$DISABLE_KEYRING" ] && [ -n "$FORCE_KEYRING" ]; then
-	error 1 BADARG "Both --no-check-gpg and --force-check-gpg specified, please pick one (at most)"
+	error 1 BADARG "Both --no-check-sig (or --no-check-gpg) and --force-check-sig (or --force-check-gpg) specified, please pick one (at most)"
 fi
 
 ###########################################################################
@@ -497,12 +499,12 @@ else
 	if ! in_path wget; then
 		error 1 NEEDWGET "You must install wget to download packages."
 	fi
-	if [ -z "$1" ] || [ -z "$2" ]; then
+	if [ -z "${1-}" ] || [ -z "${2-}" ]; then
 		usage_err 1 NEEDSUITETARGET "You must specify a suite and a target."
 	fi
 	SUITE="$1"
 	TARGET="$2"
-	USER_MIRROR="$3"
+	USER_MIRROR="${3-}"
 	TARGET="${TARGET%/}"
 	if [ "${TARGET#/}" = "${TARGET}" ]; then
 		if [ "${TARGET%/*}" = "$TARGET" ] ; then
@@ -524,7 +526,7 @@ else
 		SCRIPT="${SCRIPT}.${VARIANT}"
 		SUPPORTED_VARIANTS="$VARIANT"
 	fi
-	if [ "$4" != "" ]; then
+	if [ -n "${4-}" ]; then
 		if [ -e "$DEBOOTSTRAP_DIR/scripts/$4" ]; then
 			SCRIPT="$DEBOOTSTRAP_DIR/scripts/$4"
 		else
@@ -570,6 +572,9 @@ if [ -z "$HOST_OS" ]; then
 		FreeBSD*)
 			HOST_OS=freebsd
 		;;
+		Darwin)
+			HOST_OS=darwin
+		;;
 	esac
 fi
 
@@ -599,7 +604,7 @@ if [ "$HOST_OS" = Linux ] && ! doing_variant fakechroot && [ "$CONTAINER" = "lxc
        CHROOT_CMD="unshare --net $CHROOT_CMD"
 fi
 
-if [ -z "$SHA_SIZE" ]; then
+if [ -z "${SHA_SIZE-}" ]; then
 	SHA_SIZE=256
 fi
 if ! in_path "sha${SHA_SIZE}sum" && ! in_path "sha${SHA_SIZE}"; then
@@ -740,7 +745,7 @@ if am_doing_phase finddebs; then
 		base=$(resolve_deps "$baseX")
 		base=$(without "$base" "$required")
 
-		if [ "$LOG_EXTRA_DEPS" = true ]; then
+		if [ "${LOG_EXTRA_DEPS-}" = true ]; then
 			baseN=$(without "$baseX" "$requiredX")
 			baseU=$(without "$baseX" "$baseN")
 
@@ -875,6 +880,13 @@ fi
 if am_doing_phase kill_target; then
 	if [ "$KEEP_DEBOOTSTRAP_DIR" != true ]; then
                 info KILLTARGET "Deleting target directory"
-		rm -rf --one-file-system "$TARGET"
+		case "$HOST_OS" in
+			freebsd|darwin)
+				rm -rfx "$TARGET"
+				;;
+			*)
+				rm -rf --one-file-system "$TARGET"
+				;;
+		esac
 	fi
 fi
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,3 +1,4 @@
+# shellcheck shell=sh
 ############################################################### smallutils
 
 smallyes() {
@@ -33,6 +34,7 @@ error () {
 		for x in "$@"; do echo "EA: $x"; done
 		echo "EF: $fmt") >&4
 	else
+		# shellcheck disable=SC2059
 		(printf "E: $fmt\n" "$@") >&4
 	fi
 	exit "$err"
@@ -49,6 +51,7 @@ warning () {
 		for x in "$@"; do echo "WA: $x"; done
 		echo "WF: $fmt") >&4
 	else
+		# shellcheck disable=SC2059
 		printf "W: $fmt\n" "$@" >&4
 	fi
 }
@@ -64,6 +67,7 @@ info () {
 		for x in "$@"; do echo "IA: $x"; done
 		echo "IF: $fmt") >&4
 	else
+		# shellcheck disable=SC2059
 		printf "I: $fmt\n" "$@" >&4
 	fi
 }
@@ -71,7 +75,6 @@ info () {
 PROGRESS_NOW=0
 PROGRESS_END=0
 PROGRESS_NEXT=""
-PROGRESS_WHAT=""
 
 progress_next () {
 	PROGRESS_NEXT="$1"
@@ -91,10 +94,10 @@ wgetprogress () {
 		# non-zero exit status would cause the echo command to be
 		# skipped.  If wget succeeds, $ret will be "", so it then has to
 		# be set to a default value of 0.
-		ret=$({ { wget $@ 2>&1 >/dev/null || echo $? >&2; } | "$PKGDETAILS" "WGET%" "$PROGRESS_NOW" "$PROGRESS_NEXT" "$PROGRESS_END" >&3; } 2>&1)
-		: ${ret:=0}
+		ret=$({ { wget -U "debootstrap/$VERSION (debian-installer)" "$@" 2>&1 >/dev/null || echo $? >&2; } | "$PKGDETAILS" "WGET%" "$PROGRESS_NOW" "$PROGRESS_NEXT" "$PROGRESS_END" >&3; } 2>&1)
+		: "${ret:=0}"
 	else
-		wget ${NVSWITCH:+"$NVSWITCH"} "$@"
+		wget -U "debootstrap/$VERSION" ${NVSWITCH:+"$NVSWITCH"} "$@"
 		ret=$?
 	fi
 	return $ret
@@ -135,11 +138,11 @@ dpkg_progress () {
 	fi
 
 	dp () {
-		now=$(($now + ${1:-1}))
+		now=$((now + 1))
 	}
 
 	exitcode=0
-	while read status pkg qstate; do
+	while read -r status pkg qstate; do
 		if [ "$status" = "EXITCODE" ]; then
 			exitcode="$pkg"
 			continue
@@ -197,7 +200,7 @@ mk_download_dirs () {
 download_style () {
 	case "$1" in
 	    apt)
-		if [ "$2" = "var-state" ]; then
+		if [ "${2-}" = "var-state" ]; then
 			APTSTATE="var/state/apt"
 		else
 			APTSTATE="var/lib/apt"
@@ -233,13 +236,13 @@ keyring () {
 }
 
 detect_container () {
-	if [ "$container" = lxc ]; then
+	if [ "${container-}" = lxc ]; then
 		CONTAINER="lxc"
 	elif [ "$container" = mmdebstrap-unshare ]; then
 		CONTAINER="mmdebstrap-unshare"
 	elif grep -qs container=lxc-libvirt /proc/1/environ; then
 		CONTAINER="lxc-libvirt"
-	elif grep -qs ^systemd-nspawn$ /run/systemd/container || grep -qs systemd-nspawn /proc/1/environ || [ "$container" = "systemd-nspawn" ]; then
+	elif grep -qs ^systemd-nspawn$ /run/systemd/container || grep -qs systemd-nspawn /proc/1/environ || [ "${container-}" = "systemd-nspawn" ]; then
 		CONTAINER="systemd-nspawn"
 	elif grep -qs '[[:space:]]/docker/.*/sys/fs/cgroup' /proc/1/mountinfo || [ -e "/.dockerenv" ]; then
 		CONTAINER="docker"
@@ -261,7 +264,7 @@ SUPPORTED_VARIANTS="-"
 variants () {
 	local v
 	SUPPORTED_VARIANTS="$*"
-	for v in $*; do
+	for v in "$@"; do
 		if doing_variant "$v"; then return 0; fi
 	done
 	error 1 UNSUPPVARIANT "unsupported variant"
@@ -269,8 +272,8 @@ variants () {
 
 ########################################################### option handling
 check_conflicting_option () {
-	if ( [ "$set_what_to_do" = --foreign ] && [ "${1%%=*}" = --unpack-tarball ] ) || \
-	   ( [ "${set_what_to_do%%=*}" = "--unpack-tarball" ] && [ "$1" = --foreign ] ); then
+	if { [ "$set_what_to_do" = --foreign ] && [ "${1%%=*}" = --unpack-tarball ]; } || \
+	   { [ "${set_what_to_do%%=*}" = "--unpack-tarball" ] && [ "$1" = --foreign ]; }; then
 		LOOSEN_CONFLICTING_RESTRICTION="true"
 	elif [ -n "$set_what_to_do" ]; then
 		error 1 ARG_CONFLICTING "$set_what_to_do is specified with $1, please use only one of those options."
@@ -317,9 +320,9 @@ verify_checksum () {
 		fi
 	else
 		if in_path "sha${SHA_SIZE}sum"; then
-			relchecksum="$(sha${SHA_SIZE}sum < "$1" | sed 's/ .*$//')"
+			relchecksum="$("sha${SHA_SIZE}sum" < "$1" | sed 's/ .*$//')"
 		elif in_path "sha${SHA_SIZE}"; then
-			relchecksum="$(sha${SHA_SIZE} < "$1")"
+			relchecksum="$("sha${SHA_SIZE}" < "$1")"
 		else
 			error 1 SIGCHECK "Cannot check sha${SHA_SIZE}sum"
 		fi
@@ -336,7 +339,7 @@ get () {
 	# args: from dest [checksum size] [alt {checksum size type}]
 	# args: from dest 'byhash' [checksum size] [alt {checksum size type}]
 	local displayname
-	local versionname
+	local versionname=""
 	local from_base
 	local dest_base
 	local nocache=""
@@ -357,7 +360,7 @@ get () {
 	fi
 
 	if [ -e "$dest_base" ]; then
-		if [ -z "$1" ]; then
+		if [ -z "${1-}" ]; then
 			return 0
 		elif [ -n "$nocache" ]; then
 			rm -f "$dest_base"
@@ -374,16 +377,17 @@ get () {
 	if [ "$#" -gt 3 ]; then
 		local st=1
 		if [ "$3" = "-" ]; then st=4; fi
-		local order="$(a=$st; while [ "$a" -le $# ]; do eval echo \"\${$(($a+1))}\" $a;
-		a=$(($a + 3)); done | sort -n | sed 's/.* //')"
+		local order
+		order="$(a=$st; while [ "$a" -le $# ]; do eval "echo \"\${$((a+1))}\" $a";
+			a=$((a + 3)); done | sort -n | sed 's/.* //')"
 	else
 		local order=1
 	fi
 	for a in $order; do
 		local checksum siz typ from dest iters
-		checksum="$(eval echo \${$a})"
-		siz="$(eval echo \${$(( $a+1 ))})"
-		typ="$(eval echo \${$(( $a+2 ))})"
+		checksum="$(eval "echo \${$a-}")"
+		siz="$(eval "echo \${$(( a+1 ))-}")"
+		typ="$(eval "echo \${$(( a+2 ))-}")"
 		iters="0"
 
 		case "$typ" in
@@ -393,7 +397,7 @@ get () {
 		    *)   from="$from_base"; dest="$dest_base" ;;
 		esac
 
-		if [ ! -z "$CACHE_DIR" ]; then
+		if [ -n "$CACHE_DIR" ]; then
 			dest="${dest%%*/}"
 		elif [ "${dest#/}" = "$dest" ]; then
 			dest="./$dest"
@@ -432,7 +436,7 @@ get () {
 			else
 				rm -f "$dest2"
 				warning RETRYING "Retrying failed download of %s" "$from"
-				iters=$(($iters + 1))
+				iters=$((iters + 1))
 			fi
 		done
 		warning CORRUPTFILE "%s was corrupt" "$from"
@@ -467,7 +471,8 @@ just_get () {
 			return 1
 		fi
 	elif [ "${from#ssh:}" != "$from" ]; then
-		local ssh_dest="$(echo "$from" | sed -e 's#ssh://##' -e 's#/#:/#')"
+		local ssh_dest
+		ssh_dest="$(echo "$from" | sed -e 's#ssh://##' -e 's#/#:/#')"
 		if [ -n "$ssh_dest" ]; then
 			scp "$ssh_dest" "$dest"
 			return 0
@@ -490,7 +495,7 @@ download_indices () {
 }
 
 debfor () {
-	(while read pkg path; do
+	(while read -r pkg path; do
 		for p in "$@"; do
 			[ "$p" = "$pkg" ] || continue;
 			echo "$path"
@@ -533,7 +538,7 @@ get_release_checksum () {
 		local match="^[Ss][Hh][Aa]$SHA_SIZE:"
 	fi
 	sed -n "/$match/,/^[^ ]/p" < "$reldest" | \
-		while read a b c; do
+		while read -r a b c; do
 			if [ "$c" = "$path" ]; then echo "$a $b"; fi
 		done | head -n 1
 }
@@ -543,20 +548,20 @@ extract_release_components () {
 	local reldest="$1"; shift
 	TMPCOMPONENTS="$(sed -n 's/Components: *//p' "$reldest")"
 	for c in $TMPCOMPONENTS ; do
-		case " $COMPONENTS " in
+		case " ${COMPONENTS-} " in
 			*" $c "*) continue ;;
 		esac;
 
 		eval "
 		case \"\$c\" in
 		    $USE_COMPONENTS)
-			COMPONENTS=\"\$COMPONENTS \$c\"
+			COMPONENTS=\"\${COMPONENTS-} \$c\"
 			;;
 		esac
 		"
 	done
 
-	if [ -z "$COMPONENTS" ]; then
+	if [ -z "${COMPONENTS-}" ]; then
 		mv "$reldest" "$reldest.malformed"
 		error 1 INVALIDREL "Invalid Release file, no valid components"
 	fi
@@ -617,17 +622,17 @@ split_inline_sig () {
 	while IFS= read -r line; do
 		case "${state}" in
 		    pre-begin)
-			if [ "x${line}" = "x-----BEGIN PGP SIGNED MESSAGE-----" ]; then
+			if [ "${line}" = "-----BEGIN PGP SIGNED MESSAGE-----" ]; then
 				state="begin"
 			fi
 			;;
 		    begin)
-			if [ "x${line}" = "x" ]; then
+			if [ "${line}" = "" ]; then
 				state="data"
 			fi
 			;;
 		    data)
-			if [ "x${line}" = "x-----BEGIN PGP SIGNATURE-----" ]; then
+			if [ "${line}" = "-----BEGIN PGP SIGNATURE-----" ]; then
 				printf "%s\n" "${line}" > "$relsigdest"
 				state="signature"
 			else
@@ -637,7 +642,7 @@ split_inline_sig () {
 			;;
 		    signature)
 			printf "%s\n" "${line}" >> "$relsigdest"
-			if [ "x${line}" = "x-----END PGP SIGNATURE-----" ]; then
+			if [ "${line}" = "-----END PGP SIGNATURE-----" ]; then
 				break
 			fi
 		esac
@@ -679,10 +684,24 @@ download_release_sig () {
 		fi
 
 		info RELEASESIG "Checking Release signature"
-		# Don't worry about the exit status from gpgv; parsing the output will
-		# take care of that.
-		(gpgv --status-fd 1 --keyring "$KEYRING" --ignore-time-conflict \
-		 "$relsigdest" "$reldest" || true) | read_gpg_status
+		# If everything is installed, prefer gpgv for now
+		if in_path gpgv; then
+			# Don't worry about the exit status from gpgv; parsing the output will
+			# take care of that.
+			(gpgv --status-fd 1 --keyring "$KEYRING" --ignore-time-conflict \
+			 "$relsigdest" "$reldest" || true) | read_gpg_status
+		elif in_path sopv; then
+			local rc=0
+			sopv verify "$relsigdest" "$KEYRING" <"$reldest" || rc=$?
+			check_sop_status "$rc"
+		elif in_path sqv; then
+			local rc=0
+			sqv --keyring "$KEYRING" "$relsigdest" "$reldest" || rc=$?
+			check_sqv_status "$rc"
+		else
+			# This is already checked at argument parsing time, so shouldn't happen here
+			error 1 NEEDPGPV "none of sopv, sqv or gpgv are installed, but required for Release verification"
+		fi
 		progress 100 100 DOWNRELSIG "Downloading Release file signature"
 	fi
 }
@@ -730,7 +749,7 @@ download_release_indices () {
 					i="$gzi"
 				fi
 				if [ "$i" != "" ]; then
-					totalpkgs=$(( $totalpkgs + ${i#* } ))
+					totalpkgs=$(( totalpkgs + ${i#* } ))
 				else
 					mv "$reldest" "$reldest.malformed"
 					error 1 MISSINGRELENTRY "Invalid Release file, no entry for %s" "$subpath"
@@ -766,7 +785,7 @@ download_release_indices () {
 					ext="$ext $gzi gz"
 					i="${i:-$gzi}"
 				fi
-				progress_next $(($donepkgs + ${i#* }))
+				progress_next $((donepkgs + ${i#* }))
 				for m in $MIRRORS; do
 					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m" "$path")"
 					if get "$m/$path" "$pkgdest" $ext; then break; fi
@@ -774,7 +793,7 @@ download_release_indices () {
 				if [ ! -f "$pkgdest" ]; then
 					error 1 COULDNTDL "Couldn't download %s" "$m/$path"
 				fi
-				donepkgs=$(($donepkgs + ${i#* }))
+				donepkgs=$((donepkgs + ${i#* }))
 				progress $donepkgs $totalpkgs DOWNPKGS "Downloading Packages files"
 			done
 		done
@@ -790,13 +809,13 @@ get_package_sizes () {
 		newleft=""
 		totaldebs=0
 		countdebs=0
-		while read p details; do
+		while read -r p details; do
 			if [ "$details" = "-" ]; then
 				newleft="$newleft $p"
 			else
 				size="${details##* }";
-				totaldebs=$(($totaldebs + $size))
-				countdebs=$(($countdebs + 1))
+				totaldebs=$((totaldebs + size))
+				countdebs=$((countdebs + 1))
 			fi
 		done
 		echo "$countdebs $totaldebs$newleft"
@@ -812,19 +831,19 @@ download_debs () {
 
 	"$PKGDETAILS" PKGS "$m" "$pkgdest" "$@" | (
 		leftover=""
-		while read p ver arc mdup fil checksum size; do
+		while read -r p ver arc mdup fil checksum size; do
 			if [ "$ver" = "-" ]; then
 				leftover="$leftover $p"
 			else
-				progress_next $(($dloaddebs + $size))
+				progress_next $((dloaddebs + size))
 				debdest="$($DLDEST deb "$p" "$ver" "$arc" "$m" "$fil")"
 				debcache="$(echo "$p"_"$ver"_"$arc".deb | sed 's/:/%3a/')"
 				if [ -z "$CACHE_DIR" ] && get "$m/$fil" "$TARGET/$debdest" "$checksum" "$size"; then
-					dloaddebs=$(($dloaddebs + $size))
+					dloaddebs=$((dloaddebs + size))
 					echo >>"$TARGET/debootstrap/deburis" "$p $ver $m/$fil"
 					echo >>"$TARGET/debootstrap/debpaths" "$p $debdest"
 				elif [ -d "$CACHE_DIR" ] && get "$m/$fil" "$CACHE_DIR/$debcache" "$checksum" "$size"; then
-					dloaddebs=$(($dloaddebs + $size))
+					dloaddebs=$((dloaddebs + size))
 					echo >>"$TARGET/debootstrap/deburis" "$p $ver $m/$fil"
 					echo >>"$TARGET/debootstrap/debpaths" "$p $debdest"
 					cp "$CACHE_DIR/$debcache" "$TARGET/$debdest"
@@ -852,8 +871,8 @@ download_release () {
 	leftoverdebs="$*"
 
 	# Fix possible duplicate package names, which would screw up counts:
-	leftoverdebs=$(printf "$leftoverdebs"|tr ' ' '\n'|sort -u|tr '\n' ' ')
-	numdebs=$(printf "$leftoverdebs"|wc -w)
+	leftoverdebs=$(printf "%s" "$leftoverdebs"|tr ' ' '\n'|sort -u|tr '\n' ' ')
+	numdebs=$(printf "%s" "$leftoverdebs"|wc -w)
 
 	archs="$ARCH"
 	if [ $ARCH_ALL_SUPPORTED -eq 1 ]; then
@@ -873,7 +892,7 @@ download_release () {
 
 				leftoverdebs="$(get_package_sizes "$m1" "$pkgdest" $leftoverdebs)"
 
-				countdebs=$(($countdebs + ${leftoverdebs%% *}))
+				countdebs=$((countdebs + ${leftoverdebs%% *}))
 				leftoverdebs=${leftoverdebs#* }
 
 				totaldebs=${leftoverdebs%% *}
@@ -1004,7 +1023,7 @@ get_debs () {
 				for a in $archs; do
 					path="dists/$s/$c/binary-$a/Packages"
 					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
-					echo "$("$PKGDETAILS" FIELD "$field" "$m1" "$pkgdest" "$@" | sed 's/ .*//')"
+					"$PKGDETAILS" FIELD "$field" "$m1" "$pkgdest" "$@" | sed 's/ .*//'
 				done
 			done
 		done
@@ -1092,7 +1111,7 @@ valid_extractor () {
 choose_extractor () {
 	local extractor
 
-	if [ -n "$EXTRACTOR_OVERRIDE" ]; then
+	if [ -n "${EXTRACTOR_OVERRIDE-}" ]; then
 		extractor="$EXTRACTOR_OVERRIDE"
 	elif in_path dpkg-deb; then
 		extractor="dpkg-deb"
@@ -1118,7 +1137,7 @@ extract () { (
 	local p cat_cmd pkg
 	p=0
 	for pkg in $(debfor "$@"); do
-		p=$(($p + 1))
+		p=$((p + 1))
 		progress "$p" "$#" EXTRACTPKGS "Extracting packages"
 		packagename="$(echo "$pkg" | sed 's,^.*/,,;s,_.*$,,')"
 		info EXTRACTING "Extracting %s..." "$packagename"
@@ -1145,7 +1164,8 @@ in_target_failmsg () {
 		msg="See %s for details"
 		if [ -e "$TARGET/debootstrap/debootstrap.log" ]; then
 			arg="$TARGET/debootstrap/debootstrap.log"
-			local pkg="$(grep '^dpkg: error processing ' "$TARGET/debootstrap/debootstrap.log" | head -n 1 | sed 's/\(error processing \)\(package \|archive \)/\1/' | cut -d ' ' -f 4)"
+			local pkg
+			pkg="$(grep '^dpkg: error processing ' "$TARGET/debootstrap/debootstrap.log" | head -n 1 | sed 's/\(error processing \)\(package \|archive \)/\1/' | cut -d ' ' -f 4)"
 			if [ -n "$pkg" ]; then
 				msg="$msg (possibly the package $pkg is at fault)"
 			fi
@@ -1300,7 +1320,7 @@ setup_devices () {
 	case "$HOST_OS" in
 	    kfreebsd*)
 		;;
-	    freebsd)
+	    freebsd|darwin)
 		;;
 	    hurd*)
 		touch "$TARGET/servers/exec"
@@ -1375,14 +1395,14 @@ setup_devices_simple () {
 		warning MKNOD "Could not create /dev/ptmx, falling back to symlink. This chroot will require /dev/pts mounted with ptmxmode=666"
 		ln -sf pts/ptmx "$TARGET/dev/ptmx"
 	fi
-	ln -sf /proc/self/fd   "$TARGET/dev/fd"
+	ln -sfT /proc/self/fd   "$TARGET/dev/fd"
 	ln -sf /proc/self/fd/0 "$TARGET/dev/stdin"
 	ln -sf /proc/self/fd/1 "$TARGET/dev/stdout"
 	ln -sf /proc/self/fd/2 "$TARGET/dev/stderr"
 }
 
 setup_devices_fakechroot () {
-	rm -rf "$TARGET/dev"
+	rm -rf "${TARGET:?}/dev"
 	ln -s /dev "$TARGET"
 }
 
@@ -1480,14 +1500,6 @@ merge_usr_entry() {
 }
 
 merge_usr() {
-	if doing_variant buildd && [ -z "$MERGED_USR" ]; then
-	    case "$CODENAME" in
-		etch*|lenny|squeeze|wheezy|jessie*|stretch|buster|bullseye|bookworm)
-		    MERGED_USR="no"
-		    ;;
-	    esac
-	fi
-
 	if [ "$MERGED_USR" = "no" ]; then
 	    # With the usrmerge becoming pseudo-essential we need to use this flag
 	    # to ensure that even if it gets installed the buildd is not converted
@@ -1760,8 +1772,9 @@ resolve_deps () {
 		for a in $archs; do
 			for s in $SUITE $EXTRA_SUITES; do
 				for c in ${COMPONENTS:-$(echo "${USE_COMPONENTS}" | tr '|' ' ')}; do
-					local path="dists/$s/$c/binary-$a/Packages"
-					local pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
+					local path pkgdest
+					path="dists/$s/$c/binary-$a/Packages"
+					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
 					NEWPKGS="$NEWPKGS $("$PKGDETAILS" GETDEPS "$pkgdest" $PKGS)"
 				done
 			done
@@ -1774,8 +1787,9 @@ resolve_deps () {
 		for a in $archs; do
 			for s in $SUITE $EXTRA_SUITES; do
 				for c in ${COMPONENTS:-$(echo "${USE_COMPONENTS}" | tr '|' ' ')}; do
-					local path="dists/$s/$c/binary-$a/Packages"
-					local pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
+					local path pkgdest
+					path="dists/$s/$c/binary-$a/Packages"
+					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
 					REALPKGS="$REALPKGS $("$PKGDETAILS" PKGS REAL "$pkgdest" $PKGS | sed -n 's/ .*REAL.*$//p')"
 				done
 			done
@@ -1817,7 +1831,8 @@ setup_available () {
 }
 
 get_next_predep () {
-	local stanza="$(in_target_nofail dpkg --predep-package)"
+	local stanza
+	stanza="$(in_target_nofail dpkg --predep-package)"
 	[ "$stanza" ] || return 1
 	echo "$stanza" | grep '^Package:' | sed 's/^Package://; s/^ *//'
 }
@@ -1831,7 +1846,7 @@ check_sane_mount () {
 	mkdir -p "$1"
 
 	case "$HOST_OS" in
-	    *freebsd*|hurd*)
+	    *freebsd*|hurd*|darwin)
 		;;
 	    *)
 		if ! doing_variant fakechroot; then
@@ -1878,9 +1893,42 @@ EOF
 	return 0
 }
 
+check_sop_status () {
+	local err="$1"
+	case "$err" in
+	    0)
+		info VALIDRELSIG "Valid Release signature"
+		;;
+	    3)
+		error 1 UNKNOWNRELSIG "Release signed by unknown key\n   The specified keyring $KEYRING may be incorrect or out of date.\n   You can find the latest Debian release key at https://ftp-master.debian.org/keys.html"
+		;;
+	    41)
+		error 1 BADRELSIG "Invalid Release signature"
+		;;
+	    *)
+		error 1 SIGCHECK "Error executing sopv to check Release signature (SOP error $err)"
+		;;
+	esac
+}
+
+check_sqv_status () {
+	local err="$1"
+	case "$err" in
+	    0)
+		info VALIDRELSIG "Valid Release signature"
+		;;
+	    1)
+		error 1 BADRELSIG "Invalid Release signature"
+		;;
+	    *)
+		error 1 SIGCHECK "Error executing sqv to check Release signature (sqv error $err)"
+		;;
+	esac
+}
+
 read_gpg_status () {
 	local badsig unkkey validsig
-	while read prefix keyword keyid rest; do
+	while read -r prefix keyword keyid rest; do
 		[ "$prefix" = '[GNUPG:]' ] || continue
 		case $keyword in
 		    BADSIG)	badsig="$keyid" ;;
@@ -1914,7 +1962,7 @@ repeatn () {
 		if "$@"; then
 			break
 		else
-			n=$(( $n - 1 ))
+			n=$(( n - 1 ))
 			sleep 1
 		fi
 	done
@@ -1926,8 +1974,8 @@ N_EXIT_THINGS=0
 exit_function () {
 	local n=0
 	while [ "$n" -lt "$N_EXIT_THINGS" ]; do
-		(eval $(eval echo \${EXIT_THING_$n}) 2>/dev/null || true)
-		n=$(( $n + 1 ))
+		(eval "$(eval "echo \${EXIT_THING_$n}")" 2>/dev/null || true)
+		n=$(( n + 1 ))
 	done
 	N_EXIT_THINGS=0
 }
@@ -1939,15 +1987,15 @@ trap "exit 131" 3
 trap "exit 143" 15
 
 on_exit () {
-	eval "$(echo EXIT_THING_${N_EXIT_THINGS}=\"$1\")"
-	N_EXIT_THINGS=$(( $N_EXIT_THINGS + 1 ))
+	eval "EXIT_THING_${N_EXIT_THINGS}=\"$1\""
+	N_EXIT_THINGS=$(( N_EXIT_THINGS + 1 ))
 }
 
 ############################################################## fakechroot tools
 
 install_fakechroot_tools () {
 	if [ "$VARIANT" = "fakechroot" ]; then
-		export PATH=/usr/sbin:/sbin:$PATH
+		export PATH="/usr/sbin:/sbin:$PATH"
 	fi
 
 	mv "$TARGET/sbin/ldconfig" "$TARGET/sbin/ldconfig.REAL"
