Import the 1.0.136 release

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -50,7 +50,6 @@ CACHE_DIR=""
 INRELEASE_PATH=""
 
 DEF_MIRROR="http://deb.debian.org/debian"
-DEF_HTTPS_MIRROR="https://deb.debian.org/debian"
 
 # set $CONTAINER
 detect_container
@@ -463,7 +462,7 @@ if ! doing_variant fakechroot && command -v apt-config >/dev/null; then
     fi
     if [ -z "${http_proxy+x}" ] && [ -x "$AUTOPROXY" ]; then
         http_proxy="$($AUTOPROXY)"
-        if [ -n "$http_proxy" ]; then
+        if [ -n "$http_proxy" ] && [ "$http_proxy" != "DIRECT" ]; then
             info AUTOPROXY "Using auto-detected proxy: $http_proxy"
             export http_proxy
         fi
@@ -514,6 +513,13 @@ else
 	fi
 
 	SCRIPT="$DEBOOTSTRAP_DIR/scripts/$1"
+	if ! [ -e "$SCRIPT" ] && [ $(which distro-info 2>/dev/null) ]; then
+		if debian-distro-info --series "$1" >/dev/null 2>&1; then
+			SCRIPT="$DEBOOTSTRAP_DIR/scripts/sid"
+		elif ubuntu-distro-info --series "$1" >/dev/null 2>&1; then
+			SCRIPT="$DEBOOTSTRAP_DIR/scripts/gutsy"
+		fi
+	fi
 	if [ -n "$VARIANT" ] && [ -e "${SCRIPT}.${VARIANT}" ]; then
 		SCRIPT="${SCRIPT}.${VARIANT}"
 		SUPPORTED_VARIANTS="$VARIANT"
@@ -613,7 +619,7 @@ if am_doing_phase first_stage second_stage; then
 	fi
 	# Ensure that we can create working devices and executables on the target.
 	if ! check_sane_mount "$TARGET"; then
-		error 1 NOEXEC "Cannot install into target '$TARGET' mounted with noexec or nodev"
+		error 1 NOEXEC "Cannot install into target '$TARGET' mounted with noexec"
 	fi
 fi
 
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -217,9 +217,11 @@ keyring () {
 		if [ -e "$1" ]; then
 			KEYRING="$1"
 		elif [ -z "$DISABLE_KEYRING" ]; then
-			if [ -n "$DEF_HTTPS_MIRROR" ] && [ -z "$USER_MIRROR" ] && [ -z "$FORCE_KEYRING" ]; then
-				info KEYRING "Keyring file not available at %s; switching to https mirror %s" "$1" "$DEF_HTTPS_MIRROR"
-				USER_MIRROR="$DEF_HTTPS_MIRROR"
+			if [ -z "$USER_MIRROR" ] && [ -z "$FORCE_KEYRING" ]; then
+				if [ "http" = "${DEF_MIRROR%%://*}" ]; then
+					USER_MIRROR="https://${DEF_MIRROR#http://}"
+					info KEYRING "Keyring file not available at %s; switching to https mirror %s" "$1" "$USER_MIRROR"
+				fi
 			else
 				warning KEYRING "Cannot check Release signature; keyring file not available %s" "$1"
 				if [ -n "$FORCE_KEYRING" ]; then
@@ -1306,7 +1308,8 @@ setup_devices () {
 		touch "$TARGET/dev/console"
 		;;
 	    *)
-		if ! setup_devices_simple; then
+		if ! setup_devices_simple ||
+		   !  sh -c ': >"$1"' -- "$TARGET/dev/null" 2>/dev/null; then
 			setup_devices_bind
 		fi
 		;;
@@ -1673,7 +1676,7 @@ while (read STDIN, $x, 1) {
 }' "$@"
 		elif [ "$1" = "GETDEPS" ]; then
 			local pkgdest="$2"; shift; shift
-LC_ALL=C grep "$gropt" '^$|^Package:|^Depends:|^Pre-Depends:'  $pkgdest | perl -e '
+LC_ALL=C grep "$gropt" '^$|^Package:|^Depends:|^Pre-Depends:' "${pkgdest}" | perl -e '
 %seen = map { $_ => 1 } @ARGV;
 while (<STDIN>) {
 	if (/^Package: (.*)$/) {
@@ -1836,13 +1839,10 @@ check_sane_mount () {
 		  lxc|lxc-libvirt|mmdebstrap-unshare)
 		    ;;
 		  *)
-		    if mknod "$1/test-dev-null" c 1 3 2>/dev/null; then
-			if ! echo test > "$1/test-dev-null"; then
-			    rm -f "$1/test-dev-null"
-			    return 1
-			fi
-		    else
-			# mknod failed. Try if bind-mounting works
+		    if ! mknod "$1/test-dev-null" c 1 3 2>/dev/null ||
+		       ! echo test > "$1/test-dev-null"; then
+			# mknod failed (e.g. user namespace) or writing failed
+			# (e.g. nodev). Try if bind-mounting works
 			touch "$1/test-dev-null"
 			if ! mount -o bind /dev/null "$1/test-dev-null"; then
 			    rm -f "$1/test-dev-null"
